Repository alist-org/gofakes3, pull requests merged in 2024-07, with the labels that each got.

#3 Implement AWS Signature V2
  go.mod
  go.sum
  gofakes3.go
  signature/signature-errors.go
  signature/signature-v2-parser.go
  signature/signature-v2.go
  signature/signature-v4-parser.go
Labels: size/L

#4 Fix XML in ErrorResponse to have the correct name
  signature/signature-errors.go
Labels: size/XS

#6 Support create Dir and listBucket add Dir info
  gofakes3.go
  routing.go
Labels: size/S

#8 Fix: only add Prefix self when it's Dir.
  gofakes3.go
Labels: size/M
